### ISSUE TITLE
Package layout is confusing and over complicated

### ISSUE THREAD

**Issue by alexgleith** [digitalearthafrica/scripts#18]
The design of the project has a folder structure like `<tool-type>/tools` and `<tool-type>/tests` and there's no good place for common utils and so on.

I think it would be better just to have something like `tools/monitoring` and `tools/data` and `tools/utils.py` and so on. So that `tools/tests` could exist where there are tests for everything.

Anyhow, a better structure would be nice.

**Comment by carioca-au** [comment]
@alexgleith thank you for your suggestion, I'll be working on that soon.

**Comment by alexgleith** [comment]
Please close it by tagging it with a pull request.

**Comment by alexgleith** [comment]
Oh, this has been done without review. Got it.
